import { collection, addDoc, getDocs, serverTimestamp } from 'firebase/firestore'
import { db } from '@/firebase/config'

const products = [
  // Electronics
  {
    name: 'Wireless Bluetooth Earbuds Pro',
    slug: 'wireless-bluetooth-earbuds-pro',
    price: 12500,
    department: 'electronics',
    category: 'Audio & Sound',
    availability: 'In Stock',
    badge: 'Best Seller',
    featured: true,
    stockQuantity: 50,
    discountPercentage: 0,
    description: 'Premium wireless earbuds with deep bass and crystal-clear audio. Perfect for music, calls, and workouts.',
    longDescription: 'Experience immersive sound with these premium wireless Bluetooth earbuds. Featuring advanced noise isolation technology, these earbuds deliver deep bass and crystal-clear highs for an exceptional listening experience. The ergonomic design ensures a comfortable fit for extended wear, while the IPX4 water resistance rating makes them perfect for workouts and outdoor activities. With up to 6 hours of playback on a single charge and an additional 24 hours from the compact charging case, you can enjoy your music all day long.',
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12f8e4e12?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1598331668826-20cecc596b86?w=600&h=600&fit=crop',
    ],
    highlights: [
      { label: 'Connectivity', value: 'Bluetooth 5.3' },
      { label: 'Battery Life', value: '6 hours (30 with case)' },
      { label: 'Water Resistance', value: 'IPX4' },
      { label: 'Colour', value: 'Black' },
      { label: 'Compatibility', value: 'iOS & Android' },
    ],
  },
  {
    name: 'Smart Watch Series 5',
    slug: 'smart-watch-series-5',
    price: 35000,
    department: 'electronics',
    category: 'Smart Devices',
    availability: 'In Stock',
    badge: 'New Arrival',
    featured: true,
    stockQuantity: 25,
    discountPercentage: 0,
    description: 'Feature-packed smartwatch with health monitoring, notifications, and a stunning AMOLED display.',
    longDescription: 'Stay connected and track your health with this advanced smartwatch. The vibrant 1.75-inch AMOLED display delivers sharp visuals even in direct sunlight. Monitor your heart rate, blood oxygen levels, sleep quality, and daily activity with precision sensors. Receive notifications, control your music, and track workouts across 100+ exercise modes. The sleek metal casing and comfortable silicone band make it suitable for both casual and formal settings.',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&h=600&fit=crop',
    ],
    highlights: [
      { label: 'Display', value: '1.75" AMOLED' },
      { label: 'Battery Life', value: '7 days' },
      { label: 'Water Resistance', value: 'IP68' },
      { label: 'Colour', value: 'Midnight Black' },
      { label: 'Compatibility', value: 'iOS & Android' },
      { label: 'Sensors', value: 'Heart Rate, SpO2, Accelerometer' },
    ],
  },
  {
    name: 'Portable Bluetooth Speaker',
    slug: 'portable-bluetooth-speaker',
    price: 18000,
    department: 'electronics',
    category: 'Audio & Sound',
    availability: 'Limited Stock',
    badge: 'Best Seller',
    featured: true,
    stockQuantity: 8,
    discountPercentage: 0,
    description: 'Powerful portable speaker with 360° sound, deep bass, and rugged waterproof design.',
    longDescription: 'Take your music everywhere with this powerful portable Bluetooth speaker. Delivering rich 360° surround sound with enhanced bass, it fills any room or outdoor space with impressive audio. The rugged, waterproof IPX7 design means it can handle splashes, rain, and even submersion, making it perfect for pool parties, beach trips, and adventures. Connect two speakers for stereo sound or use the built-in microphone for hands-free calls.',
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=600&h=600&fit=crop',
    ],
    highlights: [
      { label: 'Connectivity', value: 'Bluetooth 5.0' },
      { label: 'Battery Life', value: '12 hours' },
      { label: 'Water Resistance', value: 'IPX7' },
      { label: 'Output', value: '20W' },
      { label: 'Colour', value: 'Navy Blue' },
    ],
  },
  {
    name: 'USB-C Fast Charger 65W',
    slug: 'usb-c-fast-charger-65w',
    price: 5500,
    department: 'electronics',
    category: 'Chargers & Cables',
    availability: 'In Stock',
    badge: undefined,
    featured: true,
    stockQuantity: 100,
    discountPercentage: 0,
    description: 'Compact 65W USB-C charger compatible with laptops, tablets, and phones.',
    longDescription: 'Power up your devices quickly with this compact 65W USB-C fast charger. Compatible with laptops, tablets, and smartphones, it delivers optimal charging speeds with intelligent power distribution. The foldable plug design makes it travel-friendly.',
    images: ['https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Output', value: '65W PD' },
      { label: 'Ports', value: '1x USB-C' },
      { label: 'Compatibility', value: 'Universal' },
    ],
  },
  {
    name: 'Noise Cancelling Headphones',
    slug: 'noise-cancelling-headphones',
    price: 28000,
    department: 'electronics',
    category: 'Audio & Sound',
    availability: 'In Stock',
    badge: 'New Arrival',
    featured: false,
    stockQuantity: 30,
    discountPercentage: 0,
    description: 'Over-ear headphones with active noise cancellation and premium comfort.',
    longDescription: 'Immerse yourself in pure sound with these premium over-ear headphones featuring active noise cancellation. The plush memory foam ear cushions provide hours of comfortable listening, while the ANC technology blocks ambient noise for an uninterrupted experience.',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Type', value: 'Over-ear ANC' },
      { label: 'Battery', value: '30 hours' },
      { label: 'Connectivity', value: 'Bluetooth 5.2' },
    ],
  },
  {
    name: 'Phone Screen Protector Pack',
    slug: 'phone-screen-protector-pack',
    price: 2500,
    department: 'electronics',
    category: 'Phone Accessories',
    availability: 'In Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 200,
    discountPercentage: 0,
    description: 'Tempered glass screen protectors (3-pack) for maximum clarity and protection.',
    longDescription: 'Protect your phone screen with these premium tempered glass protectors. Ultra-thin at 0.33mm with 9H hardness rating, they guard against scratches and drops without affecting touch sensitivity.',
    images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Quantity', value: '3 Pack' },
      { label: 'Hardness', value: '9H' },
      { label: 'Thickness', value: '0.33mm' },
    ],
  },
  {
    name: 'Wireless Charging Pad',
    slug: 'wireless-charging-pad',
    price: 8500,
    department: 'electronics',
    category: 'Chargers & Cables',
    availability: 'In Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 60,
    discountPercentage: 0,
    description: 'Slim wireless charging pad with fast charge support for Qi-enabled devices.',
    longDescription: 'Charge your phone effortlessly with this sleek wireless charging pad. Supporting up to 15W fast charging for compatible devices, it features LED indicators and foreign object detection for safe operation.',
    images: ['https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Speed', value: '15W max' },
      { label: 'Standard', value: 'Qi' },
    ],
  },
  {
    name: 'Tablet Stand Adjustable',
    slug: 'tablet-stand-adjustable',
    price: 6000,
    department: 'electronics',
    category: 'Laptops & Tablets',
    availability: 'Limited Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 12,
    discountPercentage: 0,
    description: 'Adjustable aluminium stand for tablets and phones with anti-slip base.',
    longDescription: 'Keep your tablet at the perfect viewing angle with this premium adjustable stand. Made from solid aluminium with a brushed finish, it supports tablets up to 12.9 inches.',
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Material', value: 'Aluminium' },
      { label: 'Compatibility', value: 'Up to 12.9"' },
    ],
  },
  {
    name: 'Smart LED Desk Lamp',
    slug: 'smart-led-desk-lamp',
    price: 14000,
    department: 'electronics',
    category: 'Smart Devices',
    availability: 'In Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 40,
    discountPercentage: 0,
    description: 'Touch-controlled LED desk lamp with adjustable brightness and colour temperature.',
    longDescription: 'Work and study in perfect lighting with this smart LED desk lamp. Features 5 colour modes and 10 brightness levels, touch controls, and a USB charging port.',
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Modes', value: '5 colour, 10 brightness' },
      { label: 'USB Port', value: 'Yes' },
    ],
  },
  {
    name: 'Type-C to HDMI Adapter',
    slug: 'type-c-to-hdmi-adapter',
    price: 4500,
    department: 'electronics',
    category: 'Chargers & Cables',
    availability: 'Out of Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 0,
    discountPercentage: 0,
    description: 'USB-C to HDMI adapter supporting 4K@60Hz output.',
    longDescription: 'Connect your laptop or phone to any HDMI display with this compact adapter. Supports 4K resolution at 60Hz for sharp presentations and media playback.',
    images: ['https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Resolution', value: '4K@60Hz' },
      { label: 'Input', value: 'USB-C' },
    ],
  },
  {
    name: 'Fitness Tracker Band',
    slug: 'fitness-tracker-band',
    price: 15000,
    department: 'electronics',
    category: 'Smart Devices',
    availability: 'In Stock',
    badge: 'Best Seller',
    featured: false,
    stockQuantity: 45,
    discountPercentage: 0,
    description: 'Lightweight fitness band with heart rate monitor and 14-day battery life.',
    longDescription: 'Track your fitness goals with this lightweight band featuring continuous heart rate monitoring, step counting, sleep tracking, and 14-day battery life.',
    images: ['https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Battery', value: '14 days' },
      { label: 'Sensors', value: 'Heart Rate, Accelerometer' },
      { label: 'Water', value: '5ATM' },
    ],
  },
  {
    name: 'Phone Case Leather Premium',
    slug: 'phone-case-leather-premium',
    price: 7500,
    department: 'electronics',
    category: 'Phone Accessories',
    availability: 'In Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 80,
    discountPercentage: 0,
    description: 'Premium leather phone case with card slot and magnetic closure.',
    longDescription: 'Protect your phone in style with this genuine leather case featuring a built-in card slot and secure magnetic closure.',
    images: ['https://images.unsplash.com/photo-1541877944-ac82a091518a?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Material', value: 'Genuine Leather' },
      { label: 'Card Slots', value: '2' },
    ],
  },
  {
    name: 'LED Bulb Pack (5W)',
    slug: 'led-bulb-pack-5w',
    price: 3500,
    department: 'electronics',
    category: 'Electrical Gadgets',
    availability: 'In Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 150,
    discountPercentage: 0,
    description: 'Energy-saving LED bulbs (pack of 3) with warm white light.',
    longDescription: 'Save energy without sacrificing brightness. This 3-pack of 5W LED bulbs provides warm white light equivalent to 40W incandescent bulbs.',
    images: ['https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Wattage', value: '5W (40W equivalent)' },
      { label: 'Quantity', value: '3 Pack' },
    ],
  },
  {
    name: 'Extension Box 4-Way',
    slug: 'extension-box-4-way',
    price: 4500,
    department: 'electronics',
    category: 'Electrical Gadgets',
    availability: 'In Stock',
    badge: 'Best Seller',
    featured: false,
    stockQuantity: 90,
    discountPercentage: 0,
    description: '4-way power extension with surge protection and 2m cable.',
    longDescription: 'Safely power multiple devices with this 4-way extension box featuring built-in surge protection and a 2-metre cable.',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Outlets', value: '4' },
      { label: 'Cable', value: '2m' },
      { label: 'Surge Protection', value: 'Yes' },
    ],
  },
  {
    name: 'Rechargeable LED Lamp',
    slug: 'rechargeable-led-lamp',
    price: 6000,
    department: 'electronics',
    category: 'Electrical Gadgets',
    availability: 'In Stock',
    badge: 'New Arrival',
    featured: false,
    stockQuantity: 55,
    discountPercentage: 0,
    description: 'Portable rechargeable LED lamp with 3 brightness levels and 8-hour runtime.',
    longDescription: 'Never be caught in the dark with this portable rechargeable LED lamp. Three brightness settings and 8 hours of runtime on a single charge.',
    images: ['https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Runtime', value: '8 hours' },
      { label: 'Brightness', value: '3 levels' },
    ],
  },
  {
    name: 'Portable Rechargeable Fan',
    slug: 'portable-rechargeable-fan',
    price: 8000,
    department: 'electronics',
    category: 'Electrical Gadgets',
    availability: 'Limited Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 10,
    discountPercentage: 0,
    description: 'Compact rechargeable desk fan with 3 speed settings.',
    longDescription: 'Stay cool anywhere with this compact rechargeable fan featuring 3 speed levels and a quiet brushless motor. USB-C charging.',
    images: ['https://images.unsplash.com/photo-1614255652498-e2b10bbfdd68?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Speeds', value: '3' },
      { label: 'Charging', value: 'USB-C' },
    ],
  },
  // Fashion
  {
    name: "Men's Cotton Boxer Briefs (3-Pack)",
    slug: 'mens-cotton-boxer-briefs-3-pack',
    price: 5500,
    department: 'fashion',
    category: "Men's Underwear",
    availability: 'In Stock',
    badge: 'Best Seller',
    featured: false,
    stockQuantity: 120,
    discountPercentage: 0,
    description: 'Comfortable cotton boxer briefs in a convenient 3-pack.',
    longDescription: 'Stay comfortable all day with these premium cotton boxer briefs. Breathable fabric with a supportive fit and flat seams for minimal irritation.',
    images: ['https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Material', value: '95% Cotton, 5% Elastane' },
      { label: 'Quantity', value: '3 Pack' },
    ],
  },
  {
    name: "Men's Singlet Vest Pack",
    slug: 'mens-singlet-vest-pack',
    price: 4000,
    department: 'fashion',
    category: "Men's Underwear",
    availability: 'In Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 90,
    discountPercentage: 0,
    description: 'Classic cotton singlet vests (3-pack) for everyday wear.',
    longDescription: 'Essential cotton singlet vests in a 3-pack. Lightweight and breathable for layering or wearing on their own.',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Material', value: '100% Cotton' },
      { label: 'Quantity', value: '3 Pack' },
    ],
  },
  {
    name: "Women's Seamless Underwear Set",
    slug: 'womens-seamless-underwear-set',
    price: 6500,
    department: 'fashion',
    category: "Women's Underwear",
    availability: 'In Stock',
    badge: 'New Arrival',
    featured: true,
    stockQuantity: 70,
    discountPercentage: 0,
    description: 'Ultra-comfortable seamless underwear set in breathable fabric. Invisible under clothing for a smooth silhouette.',
    longDescription: 'Experience all-day comfort with this seamless underwear set designed for the modern woman. Made from premium breathable microfibre fabric, these pieces are virtually invisible under clothing, giving you a smooth, confident silhouette. The seamless construction eliminates irritating seams and tags, while the wide elastic waistband stays in place without digging in. Available in neutral tones that work under any outfit.',
    images: [
      'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1606902965551-dce093cda6e7?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=600&h=600&fit=crop',
    ],
    highlights: [
      { label: 'Material', value: 'Microfibre Blend' },
      { label: 'Pieces', value: '3 Pack' },
      { label: 'Colour', value: 'Nude/Black/Grey' },
    ],
  },
  {
    name: "Women's Cotton Bralette",
    slug: 'womens-cotton-bralette',
    price: 3500,
    department: 'fashion',
    category: "Women's Underwear",
    availability: 'In Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 60,
    discountPercentage: 0,
    description: 'Soft cotton bralette with removable padding for everyday comfort.',
    longDescription: 'A comfortable everyday bralette made from soft cotton with removable padding and adjustable straps.',
    images: ['https://images.unsplash.com/photo-1606902965551-dce093cda6e7?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Material', value: 'Cotton Blend' },
      { label: 'Padding', value: 'Removable' },
    ],
  },
  {
    name: 'Premium Leather Belt',
    slug: 'premium-leather-belt',
    price: 8500,
    department: 'fashion',
    category: 'Accessories',
    availability: 'In Stock',
    badge: 'Best Seller',
    featured: true,
    stockQuantity: 50,
    discountPercentage: 0,
    description: 'Handcrafted genuine leather belt with a polished metal buckle. A timeless accessory for any wardrobe.',
    longDescription: 'Elevate your style with this handcrafted genuine leather belt. Made from carefully selected full-grain leather, this belt develops a beautiful patina over time, making it uniquely yours. The polished stainless steel buckle adds a sophisticated touch, while the precise stitching ensures long-lasting durability. Suitable for both formal and casual occasions, this versatile belt is a wardrobe essential.',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&h=600&fit=crop',
    ],
    highlights: [
      { label: 'Material', value: 'Full-Grain Leather' },
      { label: 'Buckle', value: 'Stainless Steel' },
      { label: 'Width', value: '35mm' },
      { label: 'Colour', value: 'Dark Brown' },
    ],
  },
  {
    name: 'Designer Sunglasses UV400',
    slug: 'designer-sunglasses-uv400',
    price: 15000,
    department: 'fashion',
    category: 'Accessories',
    availability: 'In Stock',
    badge: 'New Arrival',
    featured: false,
    stockQuantity: 35,
    discountPercentage: 0,
    description: 'Stylish UV400 sunglasses with polarised lenses and lightweight frame.',
    longDescription: 'Protect your eyes in style with these designer sunglasses featuring polarised UV400 lenses and a lightweight acetate frame.',
    images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Protection', value: 'UV400 Polarised' },
      { label: 'Frame', value: 'Acetate' },
    ],
  },
  {
    name: 'Gold Chain Necklace',
    slug: 'gold-chain-necklace',
    price: 12000,
    department: 'fashion',
    category: 'Jewellery',
    availability: 'In Stock',
    badge: 'Best Seller',
    featured: false,
    stockQuantity: 40,
    discountPercentage: 0,
    description: 'Elegant gold-plated chain necklace with a modern minimalist design. Hypoallergenic and tarnish-resistant.',
    longDescription: 'Make a statement with this elegant gold-plated chain necklace. Crafted with precision, this minimalist piece features a durable 18K gold plating over stainless steel that resists tarnishing and fading. The hypoallergenic material makes it safe for sensitive skin. Whether worn alone or layered with other pieces, this versatile necklace adds a touch of sophistication to any outfit. Comes in a premium gift box.',
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1515562141589-67f0d999b7f6?w=600&h=600&fit=crop',
      'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop',
    ],
    highlights: [
      { label: 'Material', value: '18K Gold Plated Stainless Steel' },
      { label: 'Length', value: '50cm' },
      { label: 'Style', value: 'Cuban Link' },
      { label: 'Colour', value: 'Gold' },
    ],
  },
  {
    name: 'Silver Stud Earrings',
    slug: 'silver-stud-earrings',
    price: 4500,
    department: 'fashion',
    category: 'Jewellery',
    availability: 'In Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 60,
    discountPercentage: 0,
    description: 'Minimalist sterling silver stud earrings for everyday elegance.',
    longDescription: 'Simple yet stunning sterling silver stud earrings. Hypoallergenic and perfect for everyday wear.',
    images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Material', value: '925 Sterling Silver' },
      { label: 'Style', value: 'Stud' },
    ],
  },
  {
    name: 'Crystal Bracelet Set',
    slug: 'crystal-bracelet-set',
    price: 7500,
    department: 'fashion',
    category: 'Jewellery',
    availability: 'Limited Stock',
    badge: 'New Arrival',
    featured: false,
    stockQuantity: 15,
    discountPercentage: 0,
    description: 'Elegant crystal bracelet set (3 pieces) for layering.',
    longDescription: 'Layer up with this beautiful set of 3 crystal bracelets. Each piece features genuine crystal beads on a stretch elastic cord.',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Pieces', value: '3' },
      { label: 'Material', value: 'Crystal & Elastic' },
    ],
  },
  {
    name: 'Satin Pyjama Set',
    slug: 'satin-pyjama-set',
    price: 9000,
    department: 'fashion',
    category: 'Nightwear',
    availability: 'In Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 30,
    discountPercentage: 0,
    description: 'Luxurious satin pyjama set with button-down top and elastic waist bottoms.',
    longDescription: 'Sleep in luxury with this smooth satin pyjama set. Features a classic button-down top with a chest pocket and matching bottoms with a comfortable elastic waist.',
    images: ['https://images.unsplash.com/photo-1573612664822-d7d347da7b80?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Material', value: 'Satin' },
      { label: 'Pieces', value: 'Top + Bottoms' },
    ],
  },
  {
    name: 'Cotton Nightgown',
    slug: 'cotton-nightgown',
    price: 6000,
    department: 'fashion',
    category: 'Nightwear',
    availability: 'In Stock',
    badge: undefined,
    featured: false,
    stockQuantity: 40,
    discountPercentage: 0,
    description: 'Soft cotton nightgown with a relaxed fit for comfortable sleep.',
    longDescription: 'Drift off in comfort with this soft cotton nightgown. The relaxed A-line fit and breathable fabric keep you cool all night.',
    images: ['https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Material', value: '100% Cotton' },
      { label: 'Fit', value: 'Relaxed' },
    ],
  },
  {
    name: "Kids' Character Pyjamas",
    slug: 'kids-character-pyjamas',
    price: 5000,
    department: 'fashion',
    category: 'Kids',
    availability: 'In Stock',
    badge: 'New Arrival',
    featured: false,
    stockQuantity: 50,
    discountPercentage: 0,
    description: 'Fun character-print pyjamas for kids in soft cotton.',
    longDescription: 'Make bedtime fun with these adorable character-print pyjamas. Made from soft, durable cotton that withstands countless washes.',
    images: ['https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600&h=600&fit=crop'],
    highlights: [
      { label: 'Material', value: 'Cotton' },
      { label: 'Ages', value: '3-10 years' },
    ],
  },
]

const categories = [
  { name: 'Phone Accessories', slug: 'phone-accessories', department: 'electronics', icon: '', image: '', description: 'Cases, chargers, screen protectors and more.' },
  { name: 'Audio & Sound', slug: 'audio-sound', department: 'electronics', icon: '', image: '', description: 'Earbuds, headphones, speakers and audio gear.' },
  { name: 'Smart Devices', slug: 'smart-devices', department: 'electronics', icon: '', image: '', description: 'Smartwatches, trackers and connected gadgets.' },
  { name: 'Chargers & Cables', slug: 'chargers-cables', department: 'electronics', icon: '', image: '', description: 'Fast chargers, adapters and cables.' },
  { name: 'Laptops & Tablets', slug: 'laptops-tablets', department: 'electronics', icon: '', image: '', description: 'Stands, accessories and peripherals.' },
  { name: 'Electrical Gadgets', slug: 'electrical-gadgets', department: 'electronics', icon: '', image: '', description: 'LED bulbs, fans, lamps and extensions.' },
  { name: "Men's Underwear", slug: 'mens-underwear', department: 'fashion', icon: '', image: '', description: 'Boxers, briefs and vests for men.' },
  { name: "Women's Underwear", slug: 'womens-underwear', department: 'fashion', icon: '', image: '', description: 'Bras, panties and seamless sets.' },
  { name: 'Accessories', slug: 'accessories', department: 'fashion', icon: '', image: '', description: 'Belts, sunglasses, bags and more.' },
  { name: 'Jewellery', slug: 'jewellery', department: 'fashion', icon: '', image: '', description: 'Necklaces, earrings, bracelets and rings.' },
  { name: 'Nightwear', slug: 'nightwear', department: 'fashion', icon: '', image: '', description: 'Pyjamas, nightgowns and loungewear.' },
  { name: 'Kids', slug: 'kids', department: 'fashion', icon: '', image: '', description: 'Clothing and accessories for children.' },
]

export async function seedProducts() {
  const existing = await getDocs(collection(db, 'products'))
  if (!existing.empty) {
    console.log(`Products collection already has ${existing.size} documents. Skipping seed.`)
    return { products: existing.size, categories: 0 }
  }

  let productCount = 0
  for (const product of products) {
    await addDoc(collection(db, 'products'), {
      ...product,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    })
    productCount++
  }

  const existingCats = await getDocs(collection(db, 'categories'))
  let catCount = 0
  if (existingCats.empty) {
    for (const cat of categories) {
      await addDoc(collection(db, 'categories'), cat)
      catCount++
    }
  }

  console.log(`Seeded ${productCount} products and ${catCount} categories.`)
  return { products: productCount, categories: catCount }
}
