export { HeroSection } from './HeroSection'
export { DepartmentSection } from './DepartmentSection'
export { CategoriesSection } from './CategoriesSection'
export { FeaturedProducts } from './FeaturedProducts'
export { WhyChooseUs } from './WhyChooseUs'
export { StoreInfo } from './StoreInfo'
export { TrustSection } from './TrustSection'
