import type { ProductCardData } from '@/components/common/ProductCard'

export interface DepartmentConfig {
  name: string
  slug: string
  description: string
  heroImage: string
  categories: string[]
}

export const departmentConfigs: Record<string, DepartmentConfig> = {
  electronics: {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Quality gadgets, phones, audio equipment and smart devices for everyday life.',
    heroImage: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=1200&h=400&fit=crop',
    categories: ['Phone Accessories', 'Audio & Sound', 'Smart Devices', 'Chargers & Cables', 'Laptops & Tablets', 'Electrical Gadgets'],
  },
  fashion: {
    name: 'Fashion',
    slug: 'fashion',
    description: 'Stylish clothing, accessories and footwear for men and women.',
    heroImage: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1200&h=400&fit=crop',
    categories: ["Men's Underwear", "Women's Underwear", 'Accessories', 'Jewellery', 'Nightwear', 'Kids'],
  },
}

export const electronicsProducts: ProductCardData[] = [
  {
    id: 'e1',
    name: 'Wireless Bluetooth Earbuds Pro',
    slug: 'wireless-bluetooth-earbuds-pro',
    price: 12500,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12f8e4e12?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    badge: 'Best Seller',
    category: 'Audio & Sound',
  },
  {
    id: 'e2',
    name: 'Smart Watch Series 5',
    slug: 'smart-watch-series-5',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: 'Smart Devices',
  },
  {
    id: 'e3',
    name: 'Portable Bluetooth Speaker',
    slug: 'portable-bluetooth-speaker',
    price: 18000,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'Limited Stock',
    badge: 'Best Seller',
    category: 'Audio & Sound',
  },
  {
    id: 'e4',
    name: 'USB-C Fast Charger 65W',
    slug: 'usb-c-fast-charger-65w',
    price: 5500,
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Chargers & Cables',
  },
  {
    id: 'e5',
    name: 'Noise Cancelling Headphones',
    slug: 'noise-cancelling-headphones',
    price: 28000,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: 'Audio & Sound',
  },
  {
    id: 'e6',
    name: 'Phone Screen Protector Pack',
    slug: 'phone-screen-protector-pack',
    price: 2500,
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Phone Accessories',
  },
  {
    id: 'e7',
    name: 'Wireless Charging Pad',
    slug: 'wireless-charging-pad',
    price: 8500,
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Chargers & Cables',
  },
  {
    id: 'e8',
    name: 'Tablet Stand Adjustable',
    slug: 'tablet-stand-adjustable',
    price: 6000,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'Limited Stock',
    category: 'Laptops & Tablets',
  },
  {
    id: 'e9',
    name: 'Smart LED Desk Lamp',
    slug: 'smart-led-desk-lamp',
    price: 14000,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Smart Devices',
  },
  {
    id: 'e10',
    name: 'Type-C to HDMI Adapter',
    slug: 'type-c-to-hdmi-adapter',
    price: 4500,
    image: 'https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'Out of Stock',
    category: 'Chargers & Cables',
  },
  {
    id: 'e11',
    name: 'Fitness Tracker Band',
    slug: 'fitness-tracker-band',
    price: 15000,
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    badge: 'Best Seller',
    category: 'Smart Devices',
  },
  {
    id: 'e12',
    name: 'Phone Case Leather Premium',
    slug: 'phone-case-leather-premium',
    price: 7500,
    image: 'https://images.unsplash.com/photo-1541877944-ac82a091518a?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Phone Accessories',
  },
  {
    id: 'e13',
    name: 'LED Bulb Pack (5W)',
    slug: 'led-bulb-pack-5w',
    price: 3500,
    image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Electrical Gadgets',
  },
  {
    id: 'e14',
    name: 'Extension Box 4-Way',
    slug: 'extension-box-4-way',
    price: 4500,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    badge: 'Best Seller',
    category: 'Electrical Gadgets',
  },
  {
    id: 'e15',
    name: 'Rechargeable LED Lamp',
    slug: 'rechargeable-led-lamp',
    price: 6000,
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: 'Electrical Gadgets',
  },
  {
    id: 'e16',
    name: 'Portable Rechargeable Fan',
    slug: 'portable-rechargeable-fan',
    price: 8000,
    image: 'https://images.unsplash.com/photo-1614255652498-e2b10bbfdd68?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'Limited Stock',
    category: 'Electrical Gadgets',
  },
]

export const fashionProducts: ProductCardData[] = [
  {
    id: 'f1',
    name: "Men's Cotton Boxer Briefs (3-Pack)",
    slug: 'mens-cotton-boxer-briefs-3-pack',
    price: 5500,
    image: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'Best Seller',
    category: "Men's Underwear",
  },
  {
    id: 'f2',
    name: "Men's Singlet Vest Pack",
    slug: 'mens-singlet-vest-pack',
    price: 4000,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    category: "Men's Underwear",
  },
  {
    id: 'f3',
    name: "Women's Seamless Underwear Set",
    slug: 'womens-seamless-underwear-set',
    price: 6500,
    image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: "Women's Underwear",
  },
  {
    id: 'f4',
    name: "Women's Cotton Bralette",
    slug: 'womens-cotton-bralette',
    price: 3500,
    image: 'https://images.unsplash.com/photo-1606902965551-dce093cda6e7?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    category: "Women's Underwear",
  },
  {
    id: 'f5',
    name: 'Premium Leather Belt',
    slug: 'premium-leather-belt',
    price: 8500,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'Best Seller',
    category: 'Accessories',
  },
  {
    id: 'f6',
    name: 'Designer Sunglasses UV400',
    slug: 'designer-sunglasses-uv400',
    price: 15000,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: 'Accessories',
  },
  {
    id: 'f7',
    name: 'Gold Chain Necklace',
    slug: 'gold-chain-necklace',
    price: 12000,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'Best Seller',
    category: 'Jewellery',
  },
  {
    id: 'f8',
    name: 'Silver Stud Earrings',
    slug: 'silver-stud-earrings',
    price: 4500,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    category: 'Jewellery',
  },
  {
    id: 'f9',
    name: 'Crystal Bracelet Set',
    slug: 'crystal-bracelet-set',
    price: 7500,
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'Limited Stock',
    badge: 'New Arrival',
    category: 'Jewellery',
  },
  {
    id: 'f10',
    name: 'Satin Pyjama Set',
    slug: 'satin-pyjama-set',
    price: 9000,
    image: 'https://images.unsplash.com/photo-1573612664822-d7d347da7b80?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    category: 'Nightwear',
  },
  {
    id: 'f11',
    name: 'Cotton Nightgown',
    slug: 'cotton-nightgown',
    price: 6000,
    image: 'https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    category: 'Nightwear',
  },
  {
    id: 'f12',
    name: "Kids' Character Pyjamas",
    slug: 'kids-character-pyjamas',
    price: 5000,
    image: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: 'Kids',
  },
]

export function getProductsByDepartment(department: string): ProductCardData[] {
  switch (department) {
    case 'electronics':
      return electronicsProducts
    case 'fashion':
      return fashionProducts
    default:
      return []
  }
}
