import type { ProductCardData } from '@/components/common/ProductCard'

export interface DepartmentConfig {
  name: string
  slug: string
  description: string
  heroImage: string
  categories: string[]
}

export const departmentConfigs: Record<string, DepartmentConfig> = {
  electronics: {
    name: 'Electronics',
    slug: 'electronics',
    description: 'Quality gadgets, phones, audio equipment and smart devices for everyday life.',
    heroImage: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=1200&h=400&fit=crop',
    categories: ['Phone Accessories', 'Audio & Sound', 'Smart Devices', 'Chargers & Cables', 'Laptops & Tablets'],
  },
  fashion: {
    name: 'Fashion',
    slug: 'fashion',
    description: 'Stylish clothing, accessories and footwear for men and women.',
    heroImage: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=1200&h=400&fit=crop',
    categories: ['Men\'s Clothing', 'Women\'s Clothing', 'Footwear', 'Accessories', 'Bags & Wallets'],
  },
}

export const electronicsProducts: ProductCardData[] = [
  {
    id: 'e1',
    name: 'Wireless Bluetooth Earbuds Pro',
    slug: 'wireless-bluetooth-earbuds-pro',
    price: 12500,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12f8e4e12?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    badge: 'Best Seller',
    category: 'Audio & Sound',
  },
  {
    id: 'e2',
    name: 'Smart Watch Series 5',
    slug: 'smart-watch-series-5',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: 'Smart Devices',
  },
  {
    id: 'e3',
    name: 'Portable Bluetooth Speaker',
    slug: 'portable-bluetooth-speaker',
    price: 18000,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'Limited Stock',
    badge: 'Best Seller',
    category: 'Audio & Sound',
  },
  {
    id: 'e4',
    name: 'USB-C Fast Charger 65W',
    slug: 'usb-c-fast-charger-65w',
    price: 5500,
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Chargers & Cables',
  },
  {
    id: 'e5',
    name: 'Noise Cancelling Headphones',
    slug: 'noise-cancelling-headphones',
    price: 28000,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: 'Audio & Sound',
  },
  {
    id: 'e6',
    name: 'Phone Screen Protector Pack',
    slug: 'phone-screen-protector-pack',
    price: 2500,
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Phone Accessories',
  },
  {
    id: 'e7',
    name: 'Wireless Charging Pad',
    slug: 'wireless-charging-pad',
    price: 8500,
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Chargers & Cables',
  },
  {
    id: 'e8',
    name: 'Tablet Stand Adjustable',
    slug: 'tablet-stand-adjustable',
    price: 6000,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'Limited Stock',
    category: 'Laptops & Tablets',
  },
  {
    id: 'e9',
    name: 'Smart LED Desk Lamp',
    slug: 'smart-led-desk-lamp',
    price: 14000,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Smart Devices',
  },
  {
    id: 'e10',
    name: 'Type-C to HDMI Adapter',
    slug: 'type-c-to-hdmi-adapter',
    price: 4500,
    image: 'https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'Out of Stock',
    category: 'Chargers & Cables',
  },
  {
    id: 'e11',
    name: 'Fitness Tracker Band',
    slug: 'fitness-tracker-band',
    price: 15000,
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    badge: 'Best Seller',
    category: 'Smart Devices',
  },
  {
    id: 'e12',
    name: 'Phone Case Leather Premium',
    slug: 'phone-case-leather-premium',
    price: 7500,
    image: 'https://images.unsplash.com/photo-1541877944-ac82a091518a?w=400&h=400&fit=crop',
    department: 'electronics',
    availability: 'In Stock',
    category: 'Phone Accessories',
  },
]

export const fashionProducts: ProductCardData[] = [
  {
    id: 'f1',
    name: 'Premium Leather Belt',
    slug: 'premium-leather-belt',
    price: 8500,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'Best Seller',
    category: 'Accessories',
  },
  {
    id: 'f2',
    name: 'Designer Sunglasses UV400',
    slug: 'designer-sunglasses-uv400',
    price: 15000,
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: 'Accessories',
  },
  {
    id: 'f3',
    name: 'Classic Canvas Sneakers',
    slug: 'classic-canvas-sneakers',
    price: 22000,
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    category: 'Footwear',
  },
  {
    id: 'f4',
    name: 'Slim Fit Chino Trousers',
    slug: 'slim-fit-chino-trousers',
    price: 12000,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: 'Men\'s Clothing',
  },
  {
    id: 'f5',
    name: 'Crossbody Leather Bag',
    slug: 'crossbody-leather-bag',
    price: 18500,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'Limited Stock',
    badge: 'Best Seller',
    category: 'Bags & Wallets',
  },
  {
    id: 'f6',
    name: 'Cotton Polo Shirt',
    slug: 'cotton-polo-shirt',
    price: 9500,
    image: 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    category: 'Men\'s Clothing',
  },
  {
    id: 'f7',
    name: 'Floral Print Midi Dress',
    slug: 'floral-print-midi-dress',
    price: 16000,
    image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'New Arrival',
    category: 'Women\'s Clothing',
  },
  {
    id: 'f8',
    name: 'Minimalist Wrist Watch',
    slug: 'minimalist-wrist-watch',
    price: 25000,
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    category: 'Accessories',
  },
  {
    id: 'f9',
    name: 'Denim Jacket Classic',
    slug: 'denim-jacket-classic',
    price: 19000,
    image: 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'Out of Stock',
    category: 'Men\'s Clothing',
  },
  {
    id: 'f10',
    name: 'Leather Wallet Bifold',
    slug: 'leather-wallet-bifold',
    price: 7000,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    category: 'Bags & Wallets',
  },
  {
    id: 'f11',
    name: 'Running Trainers Lightweight',
    slug: 'running-trainers-lightweight',
    price: 28000,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'In Stock',
    badge: 'Best Seller',
    category: 'Footwear',
  },
  {
    id: 'f12',
    name: 'Silk Scarf Printed',
    slug: 'silk-scarf-printed',
    price: 11000,
    image: 'https://images.unsplash.com/photo-1601924921557-45e8e0e5be5e?w=400&h=400&fit=crop',
    department: 'fashion',
    availability: 'Limited Stock',
    category: 'Women\'s Clothing',
  },
]

export function getProductsByDepartment(department: string): ProductCardData[] {
  switch (department) {
    case 'electronics':
      return electronicsProducts
    case 'fashion':
      return fashionProducts
    default:
      return []
  }
}
